from PyQt5 import QtCore, QtGui, QtWidgets
from menus import menus

class Ventana(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.setWindowModality(QtCore.Qt.ApplicationModal)
        MainWindow.resize(1300, 700)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        MainWindow.setMinimumSize(QtCore.QSize(1300, 700))
        MainWindow.setSizeIncrement(QtCore.QSize(2, 2))
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(-11, 9, 271, 781))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.panelDerecho = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.panelDerecho.setContentsMargins(0, 0, 0, 0)
        self.panelDerecho.setObjectName("panelDerecho")
        menu = menus() 
        self.panelDerecho.addWidget(menu) 
        self.panelPrincipal_2 = QtWidgets.QWidget(self.centralwidget)
        self.panelPrincipal_2.setGeometry(QtCore.QRect(260, 10, 2, 2))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        self.panelPrincipal_2.setSizePolicy(sizePolicy)
        self.panelPrincipal_2.setSizeIncrement(QtCore.QSize(1, 1))
        self.panelPrincipal_2.setObjectName("panelPrincipal_2")
        self.panelPrincipal = QtWidgets.QHBoxLayout(self.panelPrincipal_2)
        self.panelPrincipal.setSizeConstraint(QtWidgets.QLayout.SetMinAndMaxSize)
        self.panelPrincipal.setContentsMargins(0, 0, 0, 0)
        self.panelPrincipal.setObjectName("panelPrincipal")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1300, 26))
        self.menubar.setObjectName("menubar")
        self.menuFile = QtWidgets.QMenu(self.menubar)
        self.menuFile.setObjectName("menuFile")
        self.menuEditar = QtWidgets.QMenu(self.menubar)
        self.menuEditar.setObjectName("menuEditar")
        self.menuAyuda = QtWidgets.QMenu(self.menubar)
        self.menuAyuda.setObjectName("menuAyuda")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionNuevo = QtWidgets.QAction(MainWindow)
        self.actionNuevo.setObjectName("actionNuevo")
        self.actionAbrir = QtWidgets.QAction(MainWindow)
        self.actionAbrir.setObjectName("actionAbrir")
        self.actionGuardar = QtWidgets.QAction(MainWindow)
        self.actionGuardar.setObjectName("actionGuardar")
        self.actionSalir = QtWidgets.QAction(MainWindow)
        self.actionSalir.setObjectName("actionSalir")
        self.actionCopiar = QtWidgets.QAction(MainWindow)
        self.actionCopiar.setObjectName("actionCopiar")
        self.actionPegar = QtWidgets.QAction(MainWindow)
        self.actionPegar.setObjectName("actionPegar")
        self.actionCortar = QtWidgets.QAction(MainWindow)
        self.actionCortar.setObjectName("actionCortar")
        self.actionFusionar = QtWidgets.QAction(MainWindow)
        self.actionFusionar.setObjectName("actionFusionar")
        self.actionSegmentar = QtWidgets.QAction(MainWindow)
        self.actionSegmentar.setObjectName("actionSegmentar")
        self.actionAcerca_de = QtWidgets.QAction(MainWindow)
        self.actionAcerca_de.setObjectName("actionAcerca_de")
        self.actionAgregar_referencia_ocular = QtWidgets.QAction(MainWindow)
        self.actionAgregar_referencia_ocular.setObjectName("actionAgregar_referencia_ocular")
        self.menuFile.addAction(self.actionNuevo)
        self.menuFile.addAction(self.actionAbrir)
        self.menuFile.addAction(self.actionGuardar)
        self.menuFile.addSeparator()
        self.menuFile.addAction(self.actionSalir)
        self.menuEditar.addAction(self.actionCopiar)
        self.menuEditar.addAction(self.actionPegar)
        self.menuEditar.addAction(self.actionCortar)
        self.menuEditar.addSeparator()
        self.menuEditar.addAction(self.actionFusionar)
        self.menuEditar.addAction(self.actionSegmentar)
        self.menuEditar.addSeparator()
        self.menuEditar.addAction(self.actionAgregar_referencia_ocular)
        self.menuAyuda.addAction(self.actionAcerca_de)
        self.menubar.addAction(self.menuFile.menuAction())
        self.menubar.addAction(self.menuEditar.menuAction())
        self.menubar.addAction(self.menuAyuda.menuAction())
        
       

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "OCT-Tools"))
        self.menuFile.setTitle(_translate("MainWindow", "Archivo"))
        self.menuEditar.setTitle(_translate("MainWindow", "Editar"))
        self.menuAyuda.setTitle(_translate("MainWindow", "Ayuda"))
        self.actionNuevo.setText(_translate("MainWindow", "Nuevo"))
        self.actionAbrir.setText(_translate("MainWindow", "Abrir"))
        self.actionGuardar.setText(_translate("MainWindow", "Guardar"))
        self.actionSalir.setText(_translate("MainWindow", "Salir"))
        self.actionCopiar.setText(_translate("MainWindow", "Copiar"))
        self.actionPegar.setText(_translate("MainWindow", "Pegar"))
        self.actionCortar.setText(_translate("MainWindow", "Cortar"))
        self.actionFusionar.setText(_translate("MainWindow", "Fusionar"))
        self.actionSegmentar.setText(_translate("MainWindow", "Segmentar"))
        self.actionAcerca_de.setText(_translate("MainWindow", "Acerca de"))
        self.actionAgregar_referencia_ocular.setText(_translate("MainWindow", "Agregar referencia ocular"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ventana()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())

