from PyQt5 import QtCore, QtGui, QtWidgets

class menus(QtWidgets.QWidget):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(400, 300)
        self.botonNuevo = QtWidgets.QPushButton(Form)
        self.botonNuevo.setGeometry(QtCore.QRect(20, 20, 51, 51))
        self.botonNuevo.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("icons/if_new-file_85332.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.botonNuevo.setIcon(icon)
        self.botonNuevo.setIconSize(QtCore.QSize(30, 30))
        self.botonNuevo.setCheckable(False)
        self.botonNuevo.setObjectName("botonNuevo")
        self.botonAbrir = QtWidgets.QPushButton(Form)
        self.botonAbrir.setGeometry(QtCore.QRect(80, 20, 51, 51))
        self.botonAbrir.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("icons/if_open-file_85334.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.botonAbrir.setIcon(icon1)
        self.botonAbrir.setIconSize(QtCore.QSize(35, 36))
        self.botonAbrir.setCheckable(False)
        self.botonAbrir.setObjectName("botonAbrir")
        self.botonGuardar = QtWidgets.QPushButton(Form)
        self.botonGuardar.setGeometry(QtCore.QRect(140, 20, 51, 51))
        self.botonGuardar.setText("")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap("icons/if_floppy_285657.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.botonGuardar.setIcon(icon2)
        self.botonGuardar.setIconSize(QtCore.QSize(40, 40))
        self.botonGuardar.setCheckable(False)
        self.botonGuardar.setObjectName("botonGuardar")
        self.botonSegmentacion = QtWidgets.QToolButton(Form)
        self.botonSegmentacion.setGeometry(QtCore.QRect(80, 90, 51, 51))
        self.botonSegmentacion.setText("")
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap("icons/segmentation_icon.PNG"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.botonSegmentacion.setIcon(icon3)
        self.botonSegmentacion.setIconSize(QtCore.QSize(77, 35))
        self.botonSegmentacion.setCheckable(True)
        self.botonSegmentacion.setObjectName("botonSegmentacion")
        self.botonSegAut = QtWidgets.QPushButton(Form)
        self.botonSegAut.setGeometry(QtCore.QRect(20, 90, 51, 51))
        self.botonSegAut.setText("")
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap("icons/automated_segmentation.PNG"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.botonSegAut.setIcon(icon4)
        self.botonSegAut.setIconSize(QtCore.QSize(66, 74))
        self.botonSegAut.setObjectName("botonSegAut")
        self.botonFusionar = QtWidgets.QPushButton(Form)
        self.botonFusionar.setGeometry(QtCore.QRect(200, 20, 51, 51))
        self.botonFusionar.setText("")
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap("icons/fusion_icon.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.botonFusionar.setIcon(icon5)
        self.botonFusionar.setIconSize(QtCore.QSize(45, 45))
        self.botonFusionar.setObjectName("botonFusionar")
        self.pushButton_2 = QtWidgets.QPushButton(Form)
        self.pushButton_2.setGeometry(QtCore.QRect(140, 90, 51, 51))
        self.pushButton_2.setText("")
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap("icons/if_print_16_22615.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_2.setIcon(icon6)
        self.pushButton_2.setIconSize(QtCore.QSize(39, 39))
        self.pushButton_2.setObjectName("pushButton_2")
        self.pushButton_3 = QtWidgets.QPushButton(Form)
        self.pushButton_3.setGeometry(QtCore.QRect(200, 90, 51, 51))
        self.pushButton_3.setText("")
        icon7 = QtGui.QIcon()
        icon7.addPixmap(QtGui.QPixmap("icons/if_slice76_2831412.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_3.setIcon(icon7)
        self.pushButton_3.setIconSize(QtCore.QSize(49, 49))
        self.pushButton_3.setObjectName("pushButton_3")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = menus()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())

